
import java.awt.Point;
import java.awt.Polygon;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author atmanning
 */
public class MainJFrame extends javax.swing.JFrame {

    Point pMouse;
    Timer myTimer;
    
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        pMouse = new Point(0,0);
        
        
        // **********************  
      
                
        
        myTimer = new Timer(50, new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                gameSpacePanel1.animate();
                }
               
        });
    
        
        // **********************
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        panelWithRectangle1 = new PanelWithRectangle();
        panelWithRectangle2 = new PanelWithRectangle();
        gameSpacePanel1 = new gameSpacePanel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButtonAnimate = new javax.swing.JButton();
        jSlider1 = new javax.swing.JSlider();
        jLabelSlider1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MainJFrame.this.mouseMoved(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jButton1.setText("DrawStuff");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelWithRectangle1Layout = new javax.swing.GroupLayout(panelWithRectangle1);
        panelWithRectangle1.setLayout(panelWithRectangle1Layout);
        panelWithRectangle1Layout.setHorizontalGroup(
            panelWithRectangle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );
        panelWithRectangle1Layout.setVerticalGroup(
            panelWithRectangle1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 59, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelWithRectangle2Layout = new javax.swing.GroupLayout(panelWithRectangle2);
        panelWithRectangle2.setLayout(panelWithRectangle2Layout);
        panelWithRectangle2Layout.setHorizontalGroup(
            panelWithRectangle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        panelWithRectangle2Layout.setVerticalGroup(
            panelWithRectangle2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        gameSpacePanel1.setBackground(new java.awt.Color(204, 204, 255));
        gameSpacePanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                gameSpacePanel1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                gameSpacePanel1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout gameSpacePanel1Layout = new javax.swing.GroupLayout(gameSpacePanel1);
        gameSpacePanel1.setLayout(gameSpacePanel1Layout);
        gameSpacePanel1Layout.setHorizontalGroup(
            gameSpacePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        gameSpacePanel1Layout.setVerticalGroup(
            gameSpacePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
        );

        jButton2.setText("fly!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField1.setText("45");

        jButtonAnimate.setText("Start timer");
        jButtonAnimate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnimateActionPerformed(evt);
            }
        });

        jSlider1.setMaximum(180);
        jSlider1.setMinimum(-180);
        jSlider1.setValue(0);
        jSlider1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSlider1MouseDragged(evt);
            }
        });

        jLabelSlider1.setText("jLabel1");

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField2.setText("This is notnot");

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("click here to ontrol the ships");
        jButton5.setToolTipText("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jButton5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton5KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jButton5KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAnimate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panelWithRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(44, 44, 44))))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSlider1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelWithRectangle1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gameSpacePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButtonAnimate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelWithRectangle2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelWithRectangle1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameSpacePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSlider1))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        panelWithRectangle1.rotate(15);
        
        // add a random location rectangle
        Polygon t = new Polygon();
        int x = (int)(Math.random()*(gameSpacePanel1.getWidth()-20) );
        int y = (int)(Math.random()*(gameSpacePanel1.getHeight()-40) );
        
        
        t.addPoint(x, y);
        t.addPoint(x,y+40);
        t.addPoint(x+20,y+40);
        t.addPoint(x+20,y);
        gameSpacePanel1.addShape(t);
        
        
        // add a spaceship at the same location
        Rectangle r = new Rectangle(x,y,15,30);
        
        spaceShip s = new spaceShip( r, gameSpacePanel1 );
        s.theta = Double.parseDouble(jTextField1.getText());
        gameSpacePanel1.addShip(s);
        
        // force the panel to repaint
        gameSpacePanel1.invalidate();
        gameSpacePanel1.repaint();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        panelWithRectangle1.rotate(-10);
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        panelWithRectangle1.rotate(-10);
    }//GEN-LAST:event_formKeyReleased

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
        panelWithRectangle1.rotate(-10);
        
    }//GEN-LAST:event_formKeyTyped

    private void mouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseMoved
        // TODO add your handling code here:
        
        Point pNew = evt.getPoint();
        if( pNew.x < pMouse.x )
            panelWithRectangle1.rotate(-5);
        else
            panelWithRectangle1.rotate(5);
        
        pMouse.setLocation(pNew);
        
    }//GEN-LAST:event_mouseMoved

    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        gameSpacePanel1.animate();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonAnimateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnimateActionPerformed
        // TODO add your handling code here:
        if( myTimer.isRunning() )
            myTimer.stop();
        else
            myTimer.start();
    }//GEN-LAST:event_jButtonAnimateActionPerformed

    private void jSlider1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSlider1MouseDragged
        // TODO add your handling code here:
                 jLabelSlider1.setText("" + jSlider1.getValue());
                 gameSpacePanel1.setShipAngle(0, jSlider1.getValue());

    }//GEN-LAST:event_jSlider1MouseDragged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String s = jTextField2.getText();
        
        int nIs = 0;
        for( int i=0; i<s.length()-1; i++ )
            if( s.substring(i,i+2).equals("is") )
                nIs++;
        
        int nNot = 0;
        String s1;
        for( int i=0; i<s.length()-2; i++ ) {
            s1 = s.substring(i,i+3);
            if( s.substring(i,i+3).equals("not") )
                nNot++;
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ArrayList<String> aListNames = new ArrayList<>();
        aListNames.add("Arthur");
        aListNames.size();
        // String s1 = aListNames.get(2);

        String s2 = "Arthur";
        jButton4.setText(s2.substring(s2.length() - 2));
        for (String sName : aListNames) {; // your code }
            for (int i = 0; i < aListNames.size(); i++) {;/*code here */ }

        }
        Double d = 5.0;
        for (int i = 2; i >= -1; i--) {
            System.out.print(" " + d / i);
        }

        System.out.println("\n======");

        int i = 1;
        int j = 2;
        for (i = j; i > 0; i--) {
            System.out.print(" " + i);
        }

        System.out.println("\n======");
        String zS = "abcdefg";
        System.out.println(zS.substring(0, 3));

        System.out.println("\n======");

        System.out.println(zS.substring(zS.length() - 3, zS.length()));

        System.out.println("\n======");

        System.out.println(zS.substring(zS.length() / 2, zS.length() / 2 + 1));


    }//GEN-LAST:event_jButton4ActionPerformed

    private void gameSpacePanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gameSpacePanel1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameSpacePanel1KeyPressed

    private void gameSpacePanel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_gameSpacePanel1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_gameSpacePanel1KeyReleased

    String sKeysDown = "";

    private String strAdd(String str, char c) {
        // add char to string in alphabetical order
        for (int i = 0; i < str.length(); i++) {
            if (c < str.charAt(i)) {
                return c + str;
            }
            if (c == str.charAt(i)) {
                return str;  // char already present
            }
        }

        return str + c;  // add char to the end
    }

    private String strRemove( String str, char c ) {
        String r = "";
        for( int i=0; i<str.length(); i++ )
            if( c != str.charAt(i))
                r += str.charAt(i);
        
        return r;
    }
    
    private void jButton5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyPressed
        // TODO add your handling code here:
        
        sKeysDown = strAdd( sKeysDown, evt.getKeyChar() );
        
        jButton5.setText( sKeysDown + ".");             
               
        switch( evt.getKeyChar() ) {
            case 'l':
                gameSpacePanel1.setShipRotation(0, 10);
                break;
            case 'a':
                gameSpacePanel1.setShipRotation(0, -10);
                break;
            case ' ':
                gameSpacePanel1.shootMissile(0);
                break;
            default:
        }
    }//GEN-LAST:event_jButton5KeyPressed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton5KeyReleased
        // TODO add your handling code here
        
        sKeysDown = strRemove( sKeysDown, evt.getKeyChar() );
        jButton5.setText( sKeysDown + "." );
        
        switch( evt.getKeyChar() ) {
            case 'l':
               if (sKeysDown.contains("a") ) {
                  gameSpacePanel1.setShipRotation(0,-10);
                  break;
               }
               gameSpacePanel1.setShipRotation(0, 0);
               break;
            case 'a':
                if( sKeysDown.contains("l")) {
                    gameSpacePanel1.setShipRotation(0, 10);
                    break;
                } 
                gameSpacePanel1.setShipRotation(0, 0);
                break;
            case ' ': // don't change anything if spacebar released
                break;
            default:
                gameSpacePanel1.setShipRotation(0, 0);
        }
    }//GEN-LAST:event_jButton5KeyReleased

   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private gameSpacePanel gameSpacePanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAnimate;
    private javax.swing.JLabel jLabelSlider1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private PanelWithRectangle panelWithRectangle1;
    private PanelWithRectangle panelWithRectangle2;
    // End of variables declaration//GEN-END:variables
}
